apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: yaml-writer
spec:
  version: v0.1.0
  homepage: https://github.com/Razielt77/kubectl-yaml_writer
  shortDescription: Easily update and create k8s yaml files
  description: |
    This plugin allows you to update k8s yaml files, it will search for tha file based
    on resource kind and name and then will update an attribute and save the file.
    It can use as a programatic way to update your gitops repo.
    The plugin can also create a pair of service and deployment yaml files that can
    be used as base files to build on
  caveats: |
    * currently it supports only updates for deployment and rollout kinds. please open an issue in the repo for any request
  platforms:
    - selector:
        matchLabels:
          os: darwin
      uri: https://github.com/Razielt77/kubectl-yaml_writer/releases/download/v0.0.1/kubectl-yaml_writer_darwin.tar.gz
      sha256: cb08263b19fb72fdf4939b610a7242aa71c482747db2351738096e1080665525
      files:
        - from: "*"
          to: "."
      bin: kubectl-yaml_writer
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/Razielt77/kubectl-yaml_writer/releases/download/v0.0.1/kubectl-yaml_writer_linux.tar.gz
      sha256: 6afea0e000d34dedd9d7aa8560b84294b339e6fc4c357a9d0770ca4b3db74d06
      files:
        - from: "*"
          to: "."
      bin: kubectl-yaml_writer

