apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: yaml-writer
spec:
  version: v0.1.0
  homepage: https://github.com/Razielt77/kubectl-yaml_writer
  shortDescription: Easily update and create k8s yaml files
  description: |
    This plugin allows you to update k8s yaml files, it will search for tha file based
    on resource kind and name and then will update an attribute and save the file.
    It can use as a programatic way to update your gitops repo.
    The plugin can also create a pair of service and deployment yaml files that can
    be used as base files to build on
  caveats: |
    * currently it supports only updates for deployment and rollout kinds. please open an issue in the repo for any request
  platforms:
    - selector:
        matchLabels:
          os: darwin
      uri: https://github.com/Razielt77/kubectl-yaml_writer/releases/download/v0.0.2/kubectl-yaml_writer_darwin.tar.gz
      sha256: 2569a5e58f6130619295627dda6bfd211fae3744f78b202a4b50b06c45e72e85
      bin: kubectl-yaml_writer
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/Razielt77/kubectl-yaml_writer/releases/download/v0.0.2/kubectl-yaml_writer_linux.tar.gz
      sha256: defda1c5f07e5d3b97e748e6bea81739560350c387238ce1160b4d7b17222220
      bin: kubectl-yaml_writer

